core/urls.py
from django.urls import path

from .views import (
    ItemDetailView,
    HomeView,
    add_to_cart,
    remove_from_cart,
    ShopView,
    OrderSummaryView,
    remove_single_item_from_cart,
    CheckoutView,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    CategoryView,
    about,
    contact,
    send_mail
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('category/<slug>/', CategoryView.as_view(), name='category'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add_coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('send_mail', send_mail, name='send_mail')
]

demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% include "header.html" %}

<title>{% block head_title %}{% endblock %}</title>
{% block extra_head %} {% endblock %}
<style type="text/css">
    .form-control {
        display: block;
        width: 100%;
        height: calc(1.5em + .75rem + 2px);
        padding: .375rem .75rem;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #495057;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da !important;
        border-radius: .25rem;
        transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;
    }
</style>
<body class="animsition">
{% include "nav.html" %}

{% block content %}
{% endblock content %}

{% block extra_body %}
{% endblock %}

{% include "footer.html" %}
{% include "script.html" %}

{% block extra_scripts %}
{% endblock extra_scripts %}
<script>
    function myFunction() {
        var element = document.body;
        element.classList.toggle("dark-mode");
    }
</script>

<!--===============================================================================================-->
<script src="{% static 'temp/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'temp/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'temp/vendor/bootstrap/js/popper.js' %}"></script>
<script src="{% static 'temp/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'temp/vendor/select2/select2.min.js' %}"></script>
<script>
    $(".js-select2").each(function () {
        $(this).select2({
            minimumResultsForSearch: 20,
            dropdownParent: $(this).next('.dropDownSelect2')
        });
    })
</script>
<!--===============================================================================================-->
<script src="{% static 'temp/vendor/daterangepicker/moment.min.js' %}"></script>
<script src="{% static 'temp/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'temp/vendor/slick/slick.min.js' %}"></script>
<script src="{% static 'temp/js/slick-custom.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'temp/vendor/parallax100/parallax100.js' %}"></script>
<script>
    $('.parallax100').parallax100();
</script>
<!--===============================================================================================-->
<script src="{% static 'temp/vendor/MagnificPopup/jquery.magnific-popup.min.js' %}"></script>
<script>
    $('.gallery-lb').each(function () { // the containers for all your galleries
        $(this).magnificPopup({
            delegate: 'a', // the selector for gallery item
            type: 'image',
            gallery: {
                enabled: true
            },
            mainClass: 'mfp-fade'
        });
    });
</script>
<!--===============================================================================================-->
<script src="{% static 'temp/vendor/isotope/isotope.pkgd.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'temp/vendor/sweetalert/sweetalert.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'temp/vendor/perfect-scrollbar/perfect-scrollbar.min.js' %}"></script>
<script>
    $('.js-pscroll').each(function () {
        $(this).css('position', 'relative');
        $(this).css('overflow', 'hidden');
        var ps = new PerfectScrollbar(this, {
            wheelSpeed: 1,
            scrollingThreshold: 1000,
            wheelPropagation: false,
        });

        $(window).on('resize', function () {
            ps.update();
        })
    });
</script>
<!--===============================================================================================-->
<script src="{% static 'temp/js/main.js' %}"></script>
</body>
</html>

templates/order_snippet.html
   <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      .form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}


    </style>
  
 
    

   

    <div class="col-md-4 order-md-2 mb-4" style="background: #fff;">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
      </h4>
      <ul class="list-group mb-3">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">{{ order_item.item.title }}</h6>
            <small class="text-muted">quantity : {{ order_item.quantity }}</small>
          </div>
          <span class="text-muted">${{ order_item.get_final_price }}</span>
        </li>
        {% endfor %}
        <li class="list-group-item d-flex justify-content-between bg-light">
          <div class="text-success">
            <h6 class="my-0">Promo code</h6>
            <small>{{order.coupon.code}}</small>
          </div>
          <span class="text-success">-${{ order.coupon.amount }}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <span>Total (USD)</span>
          <strong>${{ order.get_total }}</strong>
        </li>
      </ul>
      
      {% if DISPLAY_COUPON_FORM %}
      <form method="POST" action="{% url 'core:add-coupon' %}" class="card p-2">
        {% csrf_token %}
        <div class="input-group">
          {{ couponform.code }}
          <div class="input-group-append">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </div>
      </form>
      {% endif %}
    </div>

  

templates/order_summary.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container mt-5 pt-5">
        <div class="row">
            <div class="col-lg-10 col-xl-7 m-lr-auto m-b-50 mt-5">
                <div class="m-l-25 m-r--38 m-lr-0-xl">
                    <div class="wrap-table-shopping-cart">
                        <table class="table-shopping-cart ">
                            <tr class="table_head">
                                <th class="column-1">Product</th>
                                <th class="column-2"></th>
                                <th class="column-3">Price</th>
                                <th class="column-4">Quantity</th>
                                <th class="column-5">Total</th>
                            </tr>
                            {% for order_item in object.items.all %}
                                <tr class="table_row">
                                    <td class="column-1">
                                        <div class="how-itemcart1">
                                            <img src="{{ order_item.item.image.url }}" alt="IMG">
                                        </div>
                                    </td>
                                    <td class="column-2">{{ order_item.item.title }}</td>
                                    <td class="column-3">₹{{ order_item.item.price }}</td>
                                    <td class="column-4">
                                        <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i
                                                class="fs-16 zmdi zmdi-minus mr-3"></i></a>
                                        {{ order_item.quantity }}
                                        <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i
                                                class="fs-16 zmdi zmdi-plus ml-3"></i></a>
                                    </td>
                                    <td class="column-5">
                                        {% if order_item.item.discount_price %}
                                            ${{ order_item.get_total_discount_item_price }}
                                            <span class="badge badge-primary">  Saving ${{ order_item.get_amount_saved }}</span>
                                        {% else %}
                                            ${{ order_item.get_total_item_price }}
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>

                    <div class="flex-w flex-sb-m bor15 p-t-18 p-b-15 p-lr-40 p-lr-15-sm">

                        <div class="flex-c-m stext-101 cl2 size-119 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-10">
                            <a href="/" class="text-dark">
                                Continue Shopping
                            </a>
                        </div>

                    </div>
                </div>
            </div>

            <div class="col-sm-10 col-lg-7 col-xl-5 m-lr-auto mt-5">
                <div class="bor10 p-lr-40 p-t-30 p-b-40 m-l-63 m-r-40 m-lr-0-xl p-lr-15-sm">
                    <h4 class="mtext-109 cl2 p-b-30">
                        Cart Totals
                    </h4>

                    <div class="flex-w flex-t bor12 p-b-13">
                        <div class="size-208">
								<span class="stext-110 cl2">
									Subtotal:
								</span>
                        </div>

                        <div class="size-209">
								<span class="mtext-110 cl2">
									₹{{ object.get_total }}
								</span>
                        </div>
                    </div>

                    <div class="flex-w flex-t p-t-27 p-b-33">
                        <div class="size-208">
								<span class="mtext-101 cl2">
									Total:
								</span>
                        </div>

                        <div class="size-209 p-t-1">
								<span class="mtext-110 cl2">
									₹{{ object.get_total }}
								</span>
                        </div>
                    </div>

                    <a href="/checkout"
                       class="flex-c-m stext-101 cl0 size-116 bg3 bor14 hov-btn3 p-lr-15 trans-04 pointer">
                        Proceed to Checkout
                    </a>
                </div>
            </div>
        </div>
    </div>
    {#    <div class="container">#}
    {#        <div class="row">#}
    {#            <div class="col-lg-12">#}
    {#                <h2>Order Summary</h2>#}
    {#                <table class="table">#}
    {#                    <thead>#}
    {#                    <tr>#}
    {#                        <th scope="col">#</th>#}
    {#                        <th scope="col">Product Name</th>#}
    {#                        <th scope="col">Price</th>#}
    {#                        <th scope="col">Qty</th>#}
    {#                        <th scope="col">Total Price</th>#}
    {#                    </tr>#}
    {#                    </thead>#}
    {#                    <tbody>#}
    {#                    {% for order_item in object.items.all %}#}
    {#                        <tr>#}
    {#                            <th scope="row">{{ forloop.counter }}</th>#}
    {#                            <td>#}
    {#                                <img src="{{ order_item.item.image.url }}" style="width: 130px;">#}
    {#                            </td>#}
    {#                            <td>{{ order_item.item.title }}</td>#}
    {#                            <td>{{ order_item.item.price }}</td>#}
    {#                            <td>#}
    {#                                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i#}
    {#                                        class="fas fa-minus mr-3"></i></a>#}
    {#                                {{ order_item.quantity }}#}
    {#                                <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i#}
    {#                                        class="fas fa-plus ml-3"></i></a>#}
    {#                            </td>#}
    {#                            <td>#}
    {#                                {% if order_item.item.discount_price %}#}
    {#                                    ${{ order_item.get_total_discount_item_price }}#}
    {#                                    <span class="badge badge-primary">  Saving ${{ order_item.get_amount_saved }}</span>#}
    {#                                {% else %}#}
    {#                                    ${{ order_item.get_total_item_price }}#}
    {#                                {% endif %}#}
    {#                                <a style="color: red" href="{% url 'core:remove-from-cart' order_item.item.slug %}">#}
    {#                                    <i class="fas fa-trash float-right"></i>#}
    {#                                </a>#}
    {#                            </td>#}
    {#                        </tr>#}
    {#                    {% empty %}#}
    {#                        <tr>#}
    {#                            <td colspan="5">Your cart is empty</td>#}
    {#                        </tr>#}
    {#                        </tbody>#}
    {#                    {% endfor %}#}
    {#                    {% if object.coupon %}#}
    {#                        <tr>#}
    {#                            <td colspan="5"><b>Coupon : </b></td>#}
    {#                            <td>- ${{ object.coupon.amount }}</td>#}
    {#                        </tr>#}
    {#                    {% endif %}#}
    {#                    {% if object.get_total %}#}
    {#                        <tr>#}
    {#                            <td colspan="5"><b>Order Total : </b></td>#}
    {#                            <td><b>${{ object.get_total }}</b></td>#}
    {#                        </tr>#}
    {#                        <tr>#}
    {#                            <td colspan="5">#}
    {#                                <a href="/checkout" class="btn btn-warning float-right ml-2">Checkout</a>#}
    {#                                <a href="/" class="btn btn-primary float-right">Continue Shopping</a>#}
    {##}
    {#                            </td>#}
    {#                        </tr>#}
    {#                    {% endif %}#}
    {#                </table>#}
    {#            </div>#}
    {#        </div>#}
    {#    </div>#}
    <script>
        function myFunction() {
            var element = document.body;
            element.classList.toggle("dark-mode");
        }
    </script>

    <!--===============================================================================================-->
    <script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script>
        $(".js-select2").each(function () {
            $(this).select2({
                minimumResultsForSearch: 20,
                dropdownParent: $(this).next('.dropDownSelect2')
            });
        })
    </script>
    <!--===============================================================================================-->
    <script src="{% static 'temp/vendor/daterangepicker/moment.min.js' %}"></script>
    <script src="{% static 'temp/vendor/daterangepicker/daterangepicker.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'temp/vendor/slick/slick.min.js' %}"></script>
    <script src="{% static 'temp/js/slick-custom.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'temp/vendor/parallax100/parallax100.js' %}"></script>
    <script>
        $('.parallax100').parallax100();
    </script>
    <!--===============================================================================================-->
    <script src="{% static 'temp/vendor/MagnificPopup/jquery.magnific-popup.min.js' %}"></script>
    <script>
        $('.gallery-lb').each(function () { // the containers for all your galleries
            $(this).magnificPopup({
                delegate: 'a', // the selector for gallery item
                type: 'image',
                gallery: {
                    enabled: true
                },
                mainClass: 'mfp-fade'
            });
        });
    </script>
    <!--===============================================================================================-->
    <script src="{% static 'temp/vendor/isotope/isotope.pkgd.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'temp/vendor/sweetalert/sweetalert.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'temp/vendor/perfect-scrollbar/perfect-scrollbar.min.js' %}"></script>
    <script>
        $('.js-pscroll').each(function () {
            $(this).css('position', 'relative');
            $(this).css('overflow', 'hidden');
            var ps = new PerfectScrollbar(this, {
                wheelSpeed: 1,
                scrollingThreshold: 1000,
                wheelPropagation: false,
            });

            $(window).on('resize', function () {
                ps.update();
            })
        });
    </script>
    <!--===============================================================================================-->
    <script src="{% static 'temp/js/main.js' %}"></script>

{% endblock content %}

templates/product-detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <link href="{% static 'temp/css/sty.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js"></script>
    <style>
        .newarrival {
            background: green;
            width: 50px;
            color: white;
            font-size: 12px;
            font-weight: bold;
        }

        .col-md-7 h2 {
            color: #555;
        }

        .stars {
            height: 15px;
        }

        .price {
            color: #FE980F;
            font-size: 26px;
            font-weight: bold;
            padding-top: 20px;

        }

        input {
            border: 1px solid #ccc;
            font-weight: bold;
            height: 33px;
            text-align: center;
            width: 30px;

        }

        .cart {
            background: #FE980F;
            color: #FFFFFF;
            font-size: 15px;
            margin-left: 20px;
        }
    </style>
    <!-- breadcrumb -->
    <div class="container">
        <div class="bread-crumb flex-w mt-5 pt-5">
            <a href="index.html" class="stext-109 cl8 hov-cl1 trans-04">
                Home
                <i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
            </a>

            <a href="{% url 'core:category' object.category.slug %}" class="stext-109 cl8 hov-cl1 trans-04">
                {{ object.category }}

            </a>
        </div>
    </div>
    <!-- Product Detail -->
    <section class="sec-product-detail bg0 p-t-65 p-b-60">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-lg-7 p-b-30">
                    <div class="p-l-25 p-r-30 p-lr-0-lg">
                        <div class="wrap-slick3 flex-sb flex-w">
                            <div class="wrap-slick3-dots"></div>
                            <div class="wrap-slick3-arrows flex-sb-m flex-w"></div>

                            <div class="slick3 gallery-lb">
                                <div class="item-slick3" data-thumb="{{ object.image.url }}">
                                    <div class="wrap-pic-w pos-relative">
                                        <img src="{{ object.image.url }}" alt="IMG-PRODUCT">

                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-6 col-lg-5 p-b-30">
                    <div class="p-r-50 p-t-5 p-lr-0-lg">
                        <h4 class="mtext-105 cl2 js-name-detail p-b-14">
                            {{ object.title }}
                        </h4>
                        {% if object.discount_price %}
                            <span class="mtext-106 cl2">
							₹ {{ object.discount_price }}
						</span>
                            <strike><span class="mtext-106 cl2">
							₹ {{ object.price }}
						</span></strike>
                        {% else %}
                            <span class="mtext-106 cl2">
							₹ {{ object.price }}
						</span>
                        {% endif %}
                        <br>
                        <br>
                        {% if object.is_active %}
                            <p><b>Availability:</b> In Stock </p>
                        {% else %}
                            <p><b>Availability:</b> Out of Stock </p>
                        {% endif %}
                        <p><b>Product Code:</b> {{ object.stock_no }}</p>
                        <p><b>Category:</b> {{ object.category }}</p>


                        <!--  -->
                        <div class="p-t-33">


                            <div class="flex-w flex-r-m p-b-10">
                                <div class="size-204 flex-w flex-m respon6-next">
                                    <div class="wrap-num-product flex-w m-r-20 m-tb-10">
                                        <input class="form-control size8 m-text18 t-center num-product" type="number"
                                               name="num-product"
                                               value="1">
                                    </div>

                                    <a href="{{ object.get_add_to_cart_url }}"
                                       class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04 js-addcart-detail">
                                        Add to cart
                                    </a>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <div class="bor10 m-t-50 p-t-43 p-b-40">
                <!-- Tab01 -->
                <div class="tab01">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">
                        <li class="nav-item p-b-10">
                            <a class="nav-link active" data-toggle="tab" href="#description" role="tab">Description</a>
                        </li>

                        <li class="nav-item p-b-10">
                            <a class="nav-link" data-toggle="tab" href="#information" role="tab">Additional
                                information</a>
                        </li>

                    </ul>

                    <!-- Tab panes -->
                    <div class="tab-content p-t-43">
                        <!-- - -->
                        <div class="tab-pane fade show active" id="description" role="tabpanel">
                            <div class="how-pos2 p-lr-15-md">
                                <p>
                                    {{ object.description_short }}
                                </p>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="information" role="tabpanel">
                            <div class="how-pos2 p-lr-15-md">
                                <p>
                                    {{ object.description_long }}
                                </p>
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </section>
    <script>
        function myFunction() {
            var element = document.body;
            element.classList.toggle("dark-mode");
        }
    </script>

    <!--===============================================================================================-->
    <script src="{% static 'temp/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'temp/vendor/animsition/js/animsition.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'temp/vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'temp/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'temp/vendor/select2/select2.min.js' %}"></script>
    <script>
        $(".js-select2").each(function () {
            $(this).select2({
                minimumResultsForSearch: 20,
                dropdownParent: $(this).next('.dropDownSelect2')
            });
        })
    </script>
    <!--===============================================================================================-->
    <script src="{% static 'temp/vendor/daterangepicker/moment.min.js' %}"></script>
    <script src="{% static 'temp/vendor/daterangepicker/daterangepicker.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'temp/vendor/slick/slick.min.js' %}"></script>
    <script src="{% static 'temp/js/slick-custom.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'temp/vendor/parallax100/parallax100.js' %}"></script>
    <script>
        $('.parallax100').parallax100();
    </script>
    <!--===============================================================================================-->
    <script src="{% static 'temp/vendor/MagnificPopup/jquery.magnific-popup.min.js' %}"></script>
    <script>
        $('.gallery-lb').each(function () { // the containers for all your galleries
            $(this).magnificPopup({
                delegate: 'a', // the selector for gallery item
                type: 'image',
                gallery: {
                    enabled: true
                },
                mainClass: 'mfp-fade'
            });
        });
    </script>
    <!--===============================================================================================-->
    <script src="{% static 'temp/vendor/isotope/isotope.pkgd.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'temp/vendor/sweetalert/sweetalert.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'temp/vendor/perfect-scrollbar/perfect-scrollbar.min.js' %}"></script>
    <script>
        $('.js-pscroll').each(function () {
            $(this).css('position', 'relative');
            $(this).css('overflow', 'hidden');
            var ps = new PerfectScrollbar(this, {
                wheelSpeed: 1,
                scrollingThreshold: 1000,
                wheelPropagation: false,
            });

            $(window).on('resize', function () {
                ps.update();
            })
        });
    </script>
    <!--===============================================================================================-->
    <script src="{% static 'temp/js/main.js' %}"></script>

{% endblock content %}